from flask import Flask, jsonify
from app.email_helper import send_journal_email, check_for_reply
from twilio.twiml.voice_response import VoiceResponse
from flask import send_file
from app.eleven_labs_helper import generate_eleven_labs_audio

def init_routes(app):
    @app.route('/')
    def home():
        return "Welcome to my Flask app!"
    
    @app.route('/users/<int:user_id>/journals', methods=['POST'])
    def create_journal(user_id):       
        msg_id = send_journal_email(user_id)
        return jsonify({
            "message": "Journal email sent",
            "message_id": msg_id
        }), 201

    @app.route('/journals/<message_id>', methods=['GET'])
    def get_journal_reply(message_id):
        reply = check_for_reply(message_id)
        if reply:
            return jsonify({
                "message": f"Reply found for Message-ID: {message_id}",
                "reply_content": reply
            }), 200
        else:
            return jsonify({
                "message": f"No reply found for Message-ID: {message_id}"
            }), 404
    
    @app.route("/answer", methods=['GET', 'POST'])
    def answer_call():
        """Respond to incoming phone calls with a message generated by Eleven Labs."""
        # The message we want to convert to speech
        message = "Thank you for calling! Have a great day."

        # Generate the audio using Eleven Labs
        audio_url = generate_eleven_labs_audio(message)

        # Start our TwiML response
        resp = VoiceResponse()

        # Play the generated audio to the caller
        resp.play(audio_url)

        return str(resp)
    
    @app.route('/audio/<filename>')
    def serve_audio(filename):
        """Serves the audio file."""
        return send_file(filename, mimetype='audio/mpeg')
