"""Added theme column to Entry

Revision ID: 0a27fa84e15c
Revises: 0ff8fe922f58
Create Date: 2025-02-01 12:10:24.836296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a27fa84e15c'
down_revision = '0ff8fe922f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
