"""Added new column to Podcasts

Revision ID: 60ff048aabc7
Revises: 7588d09cd59b
Create Date: 2025-02-04 19:16:47.371002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ff048aabc7'
down_revision = '7588d09cd59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('podcast_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.drop_column('podcast_duration')

    # ### end Alembic commands ###
