"""Added column to Podcast table

Revision ID: 7588d09cd59b
Revises: 5c1334a8720c
Create Date: 2025-02-04 18:45:26.886470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7588d09cd59b'
down_revision = '5c1334a8720c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('podcast_title', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.drop_column('podcast_title')

    # ### end Alembic commands ###
